"""Generate distributable web assets from user-authorized TTC files.

Usage: python scripts/package-webfonts.py /path/Hannotate.ttc /path/Hanzipen.ttc
Requires fonttools[woff]==4.60.2; not needed for normal website builds.
"""
import argparse
import json
from copy import deepcopy
from hashlib import sha256
from io import BytesIO
from itertools import groupby
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTCollection, TTFont

ROOT = Path(__file__).resolve().parents[1]
RANGES = ((0x3000, 0x303F), (0x3400, 0x9FFF), (0xF900, 0xFAFF), (0xFF00, 0xFFEF))


def chinese(code):
    return any(start <= code <= end for start, end in RANGES)


def unicode_ranges(codes):
    ranges = []
    for _, group in groupby(enumerate(sorted(codes)), lambda item: item[1] - item[0]):
        values = [code for _, code in group]
        ranges.append(f'U+{values[0]:X}' if len(values) == 1 else f'U+{values[0]:X}-{values[-1]:X}')
    return ','.join(ranges)


def write_subset(font, codes, prefix, label, output):
    face = deepcopy(font)
    # Repeated generation must not change URLs merely because the clock changed.
    face.recalcTimestamp = False
    options = subset.Options()
    options.name_IDs = ['*']
    options.name_languages = ['*']
    options.name_legacy = True
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=codes)
    sub.subset(face)
    face.flavor = 'woff2'
    buffer = BytesIO()
    face.save(buffer)
    data = buffer.getvalue()
    filename = f'{prefix}-{label}-{sha256(data).hexdigest()[:16]}.woff2'
    with TTFont(BytesIO(data)) as saved:
        assert codes == set(saved.getBestCmap()), filename
        assert saved['name'].getDebugName(6) == font['name'].getDebugName(6), filename
    (output / filename).write_bytes(data)
    return filename, len(data)


def package(source, postscript, family, prefix, common):
    collection = TTCollection(source)
    font = next(face for face in collection.fonts if face['name'].getDebugName(6) == postscript)
    supported = {code for code in font.getBestCmap() if chinese(code)}
    frequent = supported & common
    remainder = supported - frequent
    groups = [('common', frequent)] if frequent else []
    for block in sorted({code // 1024 for code in remainder}):
        groups.append((f'{block * 1024:04x}', {code for code in remainder if code // 1024 == block}))
    output = ROOT / 'public/fonts/hebi'
    output.mkdir(parents=True, exist_ok=True)
    rules = []
    covered = set()
    total = 0
    for label, codes in groups:
        filename, size = write_subset(font, codes, prefix, label, output)
        assert not covered & codes
        covered.update(codes)
        total += size
        ranges = unicode_ranges(codes)
        rules.append(f"@font-face {{ font-family: '{family}'; src: url('/fonts/hebi/{filename}') format('woff2'); font-style: normal; font-weight: 400; font-display: swap; unicode-range: {ranges}; }}")
    assert covered == supported
    print(f'{family}: {len(covered)} characters, {len(groups)} files, {total} bytes; common {len(frequent)} characters')
    collection.close()
    return rules


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('hannotate', type=Path)
    parser.add_argument('hanzipen', type=Path)
    parser.add_argument('--usage', type=Path, default=ROOT / 'scripts/webfont-usage.json',
                        help='Font-role usage collected from the built site; see collect-webfont-usage.mjs.')
    args = parser.parse_args()
    usage = json.loads(args.usage.read_text(encoding='utf-8'))
    families = ('Hebi Hand', 'Hebi Pen')
    if not isinstance(usage, dict) or any(not isinstance(usage.get(family), str) for family in families):
        parser.error('Usage JSON must contain a text string for each of Hebi Hand and Hebi Pen.')
    common = {family: {ord(char) for char in usage[family] if chinese(ord(char))} for family in families}
    rules = package(args.hannotate, 'HannotateSC-W5', 'Hebi Hand', 'hand', common['Hebi Hand'])
    rules += package(args.hanzipen, 'HanziPenSC-W3', 'Hebi Pen', 'pen', common['Hebi Pen'])
    (ROOT / 'src/styles/webfonts.css').write_text('/* Generated by scripts/package-webfonts.py; do not edit. */\n' + '\n'.join(rules) + '\n')


if __name__ == '__main__':
    main()
